services:
  ws-scylla-1: &scylla-main
    image: scylladb/scylla:5.4.6
    container_name: ws-scylla-1
    command: ['--smp=1', '--overprovisioned=1', '--developer-mode=1', '--seeds=ws-scylla-1']
    environment:
      - 'SCYLLA_JMX_ADDR=-ja 0.0.0.0'
      - 'SCYLLA_JMX_REMOTE=-r'
    ports:
      - 9040:9042
    expose:
      - 7199
    networks:
      - ws-scylla
    volumes:
      - scylla-1:/var/lib/scylla
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s -X GET --header 'Accept: application/json' 'http://localhost:10000/storage_service/native_transport'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
  ws-scylla-2: &scylla-replica
    <<: *scylla-main
    container_name: ws-scylla-2
    command: ['--smp=1', '--overprovisioned=1', '--developer-mode=1', '--seeds=ws-scylla-1']
    ports:
      - 9041:9042
    volumes:
      - scylla-2:/var/lib/scylla
    depends_on:
      ws-scylla-1:
        condition: service_healthy
  ws-scylla-3:
    <<: *scylla-replica
    container_name: ws-scylla-3
    ports:
      - 9042:9042
    volumes:
      - scylla-3:/var/lib/scylla
volumes:
  scylla-1:
    name: scylla-1
  scylla-2:
    name: scylla-2
  scylla-3:
    name: scylla-3
networks:
  ws-scylla:
    name: ws-scylla
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.5.0/24
          gateway: 10.10.5.1
    driver_opts:
      com.docker.network.bridge.name: ws-scylla
