services:
  scylla-sa-n1: &scylla-main
    image: scylladb/scylla:6.2
    container_name: scylla-sa-n1
    command:
      - --smp=2
      - --memory=2GB
      - --overprovisioned=1
      - --developer-mode=1
      - --seeds=scylla-sa-n1,scylla-eu-n1,scylla-us-n1
      - --endpoint-snitch=GossipingPropertyFileSnitch
    ports:
      - "9042:9042"
      - "19042:19042"
    expose:
      - "19042"
    networks:
      scylla-dc:
        ipv4_address: 10.9.8.2
    volumes:
      - ./rack.d/sa.properties:/etc/scylla/cassandra-rackdc.properties:rw
    healthcheck:
      test:
        - CMD-SHELL
        - cqlsh -e "SHOW VERSION" || exit 1
      interval: 15s
      timeout: 30s
      retries: 15
      start_period: 30s
  scylla-sa-n2:
    <<: *scylla-main
    container_name: scylla-sa-n2
    ports:
      - "9043:9042"
      - "19043:19042"
    networks:
      scylla-dc:
        ipv4_address: 10.9.8.3
    depends_on:
      scylla-sa-n1:
        condition: service_healthy
  scylla-sa-n3:
    <<: *scylla-main
    container_name: scylla-sa-n3
    ports:
      - "9044:9042"
      - "19044:19042"
    networks:
      scylla-dc:
        ipv4_address: 10.9.8.4
    depends_on:
      scylla-sa-n1:
        condition: service_healthy
