services:
  scylla-us-n1: &scylla-main
    image: scylladb/scylla:6.2
    container_name: scylla-us-n1
    command:
      - --smp=2
      - --memory=2GB
      - --overprovisioned=1
      - --developer-mode=1
      - --seeds=scylla-sa-n1,scylla-eu-n1,scylla-us-n1
      - --endpoint-snitch=GossipingPropertyFileSnitch
    ports:
      - "9048:9042"
      - "19048:19042"
    expose:
      - "19042"
    networks:
      scylla-dc:
        ipv4_address: 10.9.8.8
    volumes:
      - ./rack.d/us.properties:/etc/scylla/cassandra-rackdc.properties:rw
    healthcheck:
      test:
        - CMD-SHELL
        - cqlsh -e "SHOW VERSION" || exit 1
      interval: 15s
      timeout: 30s
      retries: 15
      start_period: 30s
  scylla-us-n2:
    <<: *scylla-main
    container_name: scylla-us-n2
    ports:
      - "9049:9042"
      - "19049:19042"
    networks:
      scylla-dc:
        ipv4_address: 10.9.8.9
    depends_on:
      scylla-us-n1:
        condition: service_healthy
  scylla-us-n3:
    <<: *scylla-main
    container_name: scylla-us-n3
    ports:
      - "9050:9042"
      - "19050:19042"
    networks:
      scylla-dc:
        ipv4_address: 10.9.8.10
    depends_on:
      scylla-us-n1:
        condition: service_healthy
