networks:
  scylla-dc:
    name: scylla-dc
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - gateway: 10.9.8.1
          subnet: 10.9.8.0/24
    driver_opts:
      com.docker.network.bridge.name: scylla-dc
