name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
      - name: Set up Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build the docs
        run: |
          make html
      - name: Upload artifacts
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: build/html/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: html-docs
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v4
